name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: debian:bullseye
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
          build-essential cmake qt6-base-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure build
        run: cmake -B build -DQT_VERSION=6

      - name: Compile
        run: cmake --build build --parallel

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install cmake qt5-default

      - name: Configure build
        run: cmake -B build -DQT_VERSION=5

      - name: Compile
        run: cmake --build build --parallel

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/*

  push-artifacts:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Commit and push artifacts
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git checkout -b built-artifacts
          git add .
          git commit -m 'Add built artifacts'
          git push origin built-artifacts
